filebeat.inputs:
- type: filestream
  id: my-filestream-id
  enabled: false
  paths:
    - /var/log/*.log
  reload.enabled: false
output.elasticsearch:
  hosts: ["localhost:9200"]


## Defaults
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
setup.template.settings:
  index.number_of_shards: 1
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
