- name: Generate prometheus Alert file locally
  template:
    src: alert-rule.yml
    dest: /tmp/{{COMPONENT}}-alert-rule.yml

- name: Copy Prmetheus Alert file to prometheus Server
  ansible.posix.synchronize:
    src: /tmp/{{COMPONENT}}-alert-rule.yml
    dest: /opt/prometheus/alert-rules/{{COMPONENT}}-alert-rule.yml
  delegate_to: 172.31.7.108



